### ISSUE TITLE
Code availability

### ISSUE THREAD

**Issue by defreez** [umnsec/crix#1]
Hi, your work on detecting missing checks is very interesting! The Usenix slides pointed me to this repo, but I only see the rewritten error code headers. Is the rest of the code available?

**Comment by zhanggenex** [comment]
@defreez 
As far as I know, this team rarely reply to issues or emails. So do not expect too much and save your time~

**Comment by kengiter** [comment]
We should be able to release the code in couple weeks. Thanks for your patience.

**Comment by kengiter** [comment]
@zhanggenex, thanks for your feedback. Sorry for missing your emails. We will try to improve.
