### ISSUE TITLE
License and copyright

### ISSUE THREAD

**Issue by henrirosten** [umnsec/crix#2]
Thanks for providing this project for others to experiment with. To make it clear for people considering to built upon the work you have done, I suggest you add a license and state the copyright holder. This way you set the terms under which others can reuse your software. 

Github projects without a license are not open source as explained in: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license.

Can you please add an open source license to the project?

**Comment by kengiter** [comment]
Added.
